# Ansible Inventory for Jenkins Infrastructure

# Local development environment
localhost:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3

# Remote VM deployment
docker_hosts:
  hosts:
    docker-host-vm:
      ansible_host: "{{ lookup('env', 'DOCKER_HOST_IP') | default('192.168.1.10') }}"
      ansible_user: "{{ lookup('env', 'ANSIBLE_USER') | default('ubuntu') }}"
      ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_KEY_PATH') | default('~/.ssh/id_rsa') }}"
      ansible_python_interpreter: /usr/bin/python3

# Global variables for all hosts
all:
  vars:
    # Jenkins configuration
    jenkins_version: "2.401.3-lts"
    jenkins_admin_user: "{{ lookup('env', 'JENKINS_ADMIN_USER') | default('admin') }}"
    jenkins_admin_password: "{{ lookup('env', 'JENKINS_ADMIN_PASSWORD') | default('admin123') }}"
    jenkins_master_port: 8080
    jenkins_agent_port: 50000
    
    # Corporate domain configuration
    jenkins_domain: "{{ lookup('env', 'JENKINS_DOMAIN') | default('jenkins.company.local') }}"
    jenkins_base_domain: "{{ lookup('env', 'BASE_DOMAIN') | default('company.local') }}"
    
    # Docker configuration
    docker_network_name: jenkins-network
    docker_network_subnet: "172.20.0.0/24"
    
    # SSL configuration
    jenkins_ssl_enabled: "{{ deployment_mode == 'remote' | default(false) }}"
    
    # HAProxy configuration
    haproxy_stats_password: "{{ lookup('env', 'HAPROXY_STATS_PASSWORD') | default('admin123') }}"