# Jenkins Infrastructure - Master with Static DIND Agent + Dynamic Agents
# Static DIND agent manages dynamic Python and Maven agents

version: '3.8'

services:
  # Jenkins Master/Controller
  jenkins-master:
    build:
      context: ./jenkins/master
      dockerfile: Dockerfile
    container_name: jenkins-master
    hostname: jenkins-master
    restart: unless-stopped
    
    ports:
      - "${JENKINS_MASTER_PORT:-8080}:8080"
      - "${JENKINS_AGENT_PORT:-50000}:50000"
    
    environment:
      # Jenkins admin configuration
      - JENKINS_ADMIN_ID=${JENKINS_ADMIN_USER:-admin}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD:-admin123}
      
      # JVM settings
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false 
                  -Xmx${JENKINS_MASTER_MEMORY:-2g}
                  -Xms${JENKINS_MASTER_MEMORY_MIN:-1g}
      
      # Jenkins configuration
      - JENKINS_OPTS=--httpPort=8080
      - JENKINS_SLAVE_AGENT_PORT=50000
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs
      
      # Docker settings for dynamic agents
      - DOCKER_HOST=unix:///var/run/docker.sock
      
      # Timezone
      - TZ=${TZ:-UTC}
    
    volumes:
      # Jenkins data persistence
      - jenkins_home:/var/jenkins_home
      
      # Docker socket for dynamic agent provisioning
      - /var/run/docker.sock:/var/run/docker.sock
      
      # JCasC configuration
      - ./jenkins/master/jcasc:/var/jenkins_home/casc_configs:ro
      
      # SSL certificates (if available)
      - ${CERTIFICATES_PATH:-./certificates}:/usr/local/share/ca-certificates:ro
      
      # Backup directory
      - ./backups:/backups
    
    networks:
      - jenkins-network
    
    labels:
      - "jenkins.component=master"
      - "jenkins.role=controller"
    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/login || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 120s
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Static DIND Agent for managing dynamic nodes
  jenkins-agent-dind:
    build:
      context: ./jenkins/agents
      dockerfile: Dockerfile.dind
    container_name: jenkins-agent-dind
    hostname: jenkins-agent-dind
    restart: unless-stopped
    privileged: true
    
    environment:
      # Agent connection settings
      - JENKINS_URL=http://jenkins-master:8080
      - JENKINS_AGENT_NAME=dind-agent
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
      - JENKINS_WEB_SOCKET=true
      
      # Docker settings
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_BUILDKIT=1
      - COMPOSE_DOCKER_CLI_BUILD=1
      
      # Agent configuration
      - JENKINS_TUNNEL=jenkins-master:50000
      - JENKINS_PROTOCOLS=JNLP4-connect
      
      # Resource limits
      - JAVA_OPTS=-Xmx1g -Xms512m
      
      # Timezone
      - TZ=${TZ:-UTC}
    
    volumes:
      # Docker socket access (privileged for DIND operations)
      - /var/run/docker.sock:/var/run/docker.sock
      
      # Agent workspace
      - jenkins_agent_dind_workspace:/home/jenkins/agent
      
      # Docker data for DIND operations
      - jenkins_docker_data:/var/lib/docker
      
      # Shared workspace for dynamic agents
      - jenkins_shared_workspace:/shared/workspace
      
      # SSL certificates
      - ${CERTIFICATES_PATH:-./certificates}:/usr/local/share/ca-certificates:ro
    
    networks:
      - jenkins-network
    
    depends_on:
      jenkins-master:
        condition: service_healthy
    
    labels:
      - "jenkins.component=agent"
      - "jenkins.agent.type=static"
      - "jenkins.agent.role=dind"
      - "jenkins.agent.labels=dind,docker-manager,static,privileged"
    
    user: "1000:1000"
    
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

networks:
  jenkins-network:
    name: jenkins-network
    driver: bridge
    ipam:
      config:
        - subnet: ${JENKINS_NETWORK_SUBNET:-172.20.0.0/24}

volumes:
  # Jenkins master data
  jenkins_home:
    name: jenkins_home
    driver: local
  
  # DIND agent workspace
  jenkins_agent_dind_workspace:
    name: jenkins_agent_dind_workspace
    driver: local
  
  # Docker data for DIND operations
  jenkins_docker_data:
    name: jenkins_docker_data
    driver: local
  
  # Shared workspace for dynamic agents
  jenkins_shared_workspace:
    name: jenkins_shared_workspace
    driver: local
  
  # Shared caches for dynamic agents
  maven-cache:
    name: maven-cache
    driver: local
  
  pip-cache:
    name: pip-cache
    driver: local
  
  jenkins-workspace:
    name: jenkins-workspace
    driver: local