# Jenkins Configuration as Code (JCasC)
# Simplified configuration for Docker-based CI/CD with Python and Maven dynamic nodes

jenkins:
  systemMessage: "Jenkins Master - Docker-based CI/CD Environment\nConfigured via Configuration as Code"
  
  # No executors on master - use agents only
  numExecutors: 0
  
  # Security configuration
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${JENKINS_ADMIN_ID:-admin}"
          password: "${JENKINS_ADMIN_PASSWORD:-admin123}"

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - "${JENKINS_ADMIN_ID:-admin}"
          - name: "developer"
            description: "Developers with build permissions"
            permissions:
              - "Overall/Read"
              - "Job/Build"
              - "Job/Cancel"
              - "Job/Read"
              - "Job/Workspace"
              - "View/Read"
            assignments:
              - "authenticated"

  # Static nodes configuration
  nodes:
    - permanent:
        name: "dind-agent"
        description: "Static Docker-in-Docker agent for managing dynamic nodes"
        numExecutors: 2
        mode: NORMAL
        labelString: "dind docker-manager static privileged"
        remoteFS: "/home/jenkins/agent"
        launcher:
          inbound:
            workDirSettings:
              disabled: false
              failIfWorkDirIsMissing: false
              internalDir: "remoting"
        retentionStrategy: "always"
        nodeProperties:
          - envVars:
              env:
                - key: "DOCKER_HOST"
                  value: "unix:///var/run/docker.sock"
                - key: "DOCKER_BUILDKIT"
                  value: "1"

  # Global environment variables
  globalNodeProperties:
    - envVars:
        env:
          - key: "DOCKER_HOST"
            value: "unix:///var/run/docker.sock"

  # Docker Cloud for dynamic agents
  clouds:
    - docker:
        name: "docker-cloud"
        dockerApi:
          dockerHost:
            uri: "unix:///var/run/docker.sock"
        templates:
          # Maven/Java dynamic agent
          - labelString: "maven java dynamic"
            dockerTemplateBase:
              image: "jenkins/inbound-agent:latest-maven"
              mounts:
                - "type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock"
                - "type=volume,source=maven-cache,destination=/home/jenkins/.m2"
                - "type=volume,source=jenkins-workspace,destination=/home/jenkins/agent"
              environmentsString: |
                JAVA_HOME=/opt/java/openjdk-11
                MAVEN_OPTS=-Xmx2g -Xms512m
                DOCKER_HOST=unix:///var/run/docker.sock
                JENKINS_AGENT_WORKDIR=/home/jenkins/agent
            remoteFs: "/home/jenkins/agent"
            connector:
              attach:
                user: "jenkins"
            instanceCapStr: "5"
            retentionStrategy:
              idleMinutes: 10
            removeVolumes: true
            pullStrategy: PULL_LATEST

          # Python dynamic agent  
          - labelString: "python py dynamic"
            dockerTemplateBase:
              image: "jenkins/inbound-agent:latest-python"
              mounts:
                - "type=bind,source=/var/run/docker.sock,destination=/var/run/docker.sock"
                - "type=volume,source=pip-cache,destination=/home/jenkins/.cache/pip"
                - "type=volume,source=jenkins-workspace,destination=/home/jenkins/agent"
              environmentsString: |
                PYTHONPATH=/usr/local/lib/python3.9/site-packages
                PIP_CACHE_DIR=/home/jenkins/.cache/pip
                DOCKER_HOST=unix:///var/run/docker.sock
                JENKINS_AGENT_WORKDIR=/home/jenkins/agent
            remoteFs: "/home/jenkins/agent"
            connector:
              attach:
                user: "jenkins"
            instanceCapStr: "5"
            retentionStrategy:
              idleMinutes: 10
            removeVolumes: true
            pullStrategy: PULL_LATEST

# Global tool configurations
tool:
  maven:
    installations:
      - name: "Maven-3.9"
        home: "/opt/maven"
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.9.4"

  git:
    installations:
      - name: "Default Git"
        home: "git"

  jdk:
    installations:
      - name: "OpenJDK-11"
        home: "/opt/java/openjdk"
        properties:
          - installSource:
              installers:
                - adoptOpenJdkInstaller:
                    id: "jdk-11.0.16+8"

# Additional configurations
unclassified:
  # Email configuration (basic)
  mailer:
    defaultSuffix: "@company.com"
    smtpHost: "localhost"
    smtpPort: "25"

  # Pipeline configuration for performance
  globalDefaultFlowDurabilityLevel:
    durabilityHint: PERFORMANCE_OPTIMIZED

  # Git global configuration
  gitSCM:
    globalConfigName: "Jenkins"
    globalConfigEmail: "jenkins@company.com"